name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-6517c2b93696b100381c171a-62832543d9c379ba6453dc6053a48777a9
      - name: Run API tests
        run: |
          postman collection run "16102624-123fca07-5048-431f-b405-11d2239a2779" --integration-id "149407-${{ github.run_id }}"